/*
* Copyright 2025 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this 
* software and associated documentation files (the "Software"), to deal in the Software 
* without restriction, including without limitation the rights to use, copy, modify, merge, 
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons 
* to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or 
* substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
using System.Collections.Generic;

namespace o2g.Types.RecordingNS
{
    /// <summary>
    /// Represent a call on a recordable device. A call is identified by its <see cref="CallRef"/>, a unique <see langword="string"/> generated by the O2G server.
    /// </summary>
    public class ActiveCall
    {
        /// <summary>
        /// This property is the reference of this call.
        /// </summary>
        /// <value>
        /// The unique <see langword="string"/> value that identifies this call.
        /// </value>
        public string CallRef { get; init; }

        /// <summary>
        /// This property gives the recording state for this call.
        /// </summary>
        /// <value>
        /// A <see cref="RecordingState"/> that represents the recording state.
        /// </value>
        public RecordingState RecordingState { get; init; }


        /// <summary>
        /// Indicate which recording action can be done on the call.
        /// </summary>
        /// <value>
        /// A <see cref="RecordingAction"/> that represents the possible recording action.
        /// </value>
        public RecordingAction Action { get; init; }
    }
}
