/*
* Copyright 2021 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this
* software and associated documentation files (the "Software"), to deal in the Software
* without restriction, including without limitation the rights to use, copy, modify, merge,
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
* to whom the Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all copies or
* substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
using o2g.Events;
using o2g.Events.CommunicationLog;
using o2g.Internal.Services;
using o2g.Types.CommunicationLogNS;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace o2g
{
    /// <summary>
    /// The <c>ICommunicationLog</c> service provides operations to retrieve, manage, and manipulate
    /// a user's communication log (com records).
    /// Using this service requires having a <b>TELEPHONY_ADVANCED</b> license.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Communication records are generated by the O2G server and provide detailed information about
    /// calls, participants, call outcomes, and durations. The communication log has a depth of
    /// 100 records maximum per user; when the limit is reached, the oldest records are removed.
    /// </para>
    /// <para>
    /// Acknowledgement and unacknowledgement of an incoming missed call using O2G is
    /// <b>NOT synchronized</b> with the OmniPCX Enterprise.
    /// </para>
    /// </remarks>
    public interface ICommunicationLog : IService
    {
        /// <summary>
        /// Occurs when a new comlog entry has been created.
        /// </summary>
        public event EventHandler<O2GEventArgs<OnComRecordCreatedEvent>> ComRecordCreated;

        /// <summary>
        /// Occurs when one or more records have been modified.
        /// </summary>
        public event EventHandler<O2GEventArgs<OnComRecordModifiedEvent>> ComRecordModified;

        /// <summary>
        /// Occurs when one or more call log records have been deleted.
        /// </summary>
        public event EventHandler<O2GEventArgs<OnComRecordsDeletedEvent>> ComRecordsDeleted;

        /// <summary>
        /// Occurs when one or more unanswered comlog records have been acknowledged.
        /// </summary>
        public event EventHandler<O2GEventArgs<OnComRecordsAckEvent>> ComRecordsAck;

        /// <summary>
        /// Occurs when one or more unanswered comlog records have been unacknowledged.
        /// </summary>
        public event EventHandler<O2GEventArgs<OnComRecordsUnAckEvent>> ComRecordsUnAck;

        /// <summary>
        /// Retrieves communication records based on the specified criteria, with pagination support
        /// and optional optimization.
        /// </summary>
        /// <param name="filter">The filter describing the query criteria.</param>
        /// <param name="page">Optional page description.</param>
        /// <param name="optimized"><see langword="true"/> to enable optimization.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// A <see cref="QueryResult"/> containing the matching com records; <see langword="null"/> in case of error.
        /// </returns>
        /// <remarks>
        /// <para>
        /// When <c>optimized</c> is set to <see langword="true"/>, the query returns the full identity of a
        /// participant only the first time it appears in the records. Subsequent occurrences of the same
        /// participant will only include minimal identification (e.g., phone number).
        /// </para>
        /// <para>
        /// The <c>page</c> parameter of type <see cref="Page"/> allows querying the communication log page
        /// by page. The <see cref="QueryResult"/> includes the records, paging information, and the total
        /// number of matching records.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <example>
        /// This example shows how to use the <c>Page</c> object to retrieve com records.
        /// <code>
        ///     ICommunicationLog comLog = myApp.CommunicationLogService;
        ///
        ///     Page page = new()
        ///     {
        ///         Offset = 0,
        ///         Limit = 10
        ///     }
        ///
        ///     for (;;)
        ///     {
        ///         QueryResult result = await comLog.GetComRecordsAsync(null, page);
        ///
        ///         // Display page of result
        ///         if (result.Count > (page.Offset + page.Limit))
        ///         {
        ///             // Load next page
        ///             page.Next();
        ///
        ///             // Wait for a user action (e.g., button click) and load the next page.
        ///         }
        ///         else
        ///         {
        ///             // End of pages — stop.
        ///         }
        ///     }
        /// </code>
        /// </example>
        Task<QueryResult> GetComRecordsAsync(QueryFilter filter = null, Page page = null, bool optimized = false, string loginName = null);

        /// <summary>
        /// Retrieves the communication record with the specified identifier.
        /// </summary>
        /// <param name="recordId">The com record identifier.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// The <see cref="ComRecord"/> with the requested identifier; <see langword="null"/> in case of error
        /// or if no com record with the specified identifier exists.
        /// </returns>
        /// <remarks>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </remarks>
        Task<ComRecord> GetComRecordAsync(long recordId, string loginName = null);

        /// <summary>
        /// Deletes the communication record with the specified identifier.
        /// </summary>
        /// <param name="recordId">The com record identifier.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// <see langword="true"/> in case of success; <see langword="false"/> otherwise.
        /// </returns>
        /// <remarks>
        /// <para>
        /// A <see cref="ComRecordsDeleted"/> event is raised when the deletion succeeds.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <seealso cref="ComRecordsDeleted"/>
        Task<bool> DeleteComRecordAsync(long recordId, string loginName = null);

        /// <summary>
        /// Deletes the communication records matching the specified filter.
        /// </summary>
        /// <param name="filter">The filter describing which records to delete.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// <see langword="true"/> in case of success; <see langword="false"/> otherwise.
        /// </returns>
        /// <remarks>
        /// <para>
        /// The <c>filter</c> parameter of type <see cref="QueryFilter"/> defines the search criteria for
        /// the delete operation. A <see cref="ComRecordsDeleted"/> event is raised listing the deleted
        /// com records.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <seealso cref="ComRecordsDeleted"/>
        Task<bool> DeleteComRecordsAsync(QueryFilter filter = null, string loginName = null);

        /// <summary>
        /// Deletes the communication records with the specified identifiers.
        /// </summary>
        /// <param name="recordIds">The list of com record identifiers to delete.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// <see langword="true"/> in case of success; <see langword="false"/> otherwise.
        /// </returns>
        /// <remarks>
        /// <para>
        /// A <see cref="ComRecordsDeleted"/> event is raised listing the identifiers of the com records
        /// that were actually deleted.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <seealso cref="ComRecordsDeleted"/>
        Task<bool> DeleteComRecordsAsync(List<long> recordIds, string loginName = null);

        /// <summary>
        /// Acknowledges the communication records with the specified identifiers.
        /// </summary>
        /// <param name="recordIds">The list of com record identifiers to acknowledge.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// <see langword="true"/> in case of success; <see langword="false"/> otherwise.
        /// </returns>
        /// <remarks>
        /// <para>
        /// A <see cref="ComRecordsAck"/> event is raised listing the identifiers of the com records
        /// that were actually acknowledged.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <seealso cref="ComRecordsAck"/>
        Task<bool> AcknowledgeComRecordsAsync(List<long> recordIds, string loginName = null);

        /// <summary>
        /// Acknowledges the communication record with the specified identifier.
        /// </summary>
        /// <param name="recordId">The com record identifier.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// <see langword="true"/> in case of success; <see langword="false"/> otherwise.
        /// </returns>
        /// <remarks>
        /// <para>
        /// A <see cref="ComRecordsAck"/> event is raised listing the identifiers of the com records
        /// that were actually acknowledged.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <seealso cref="AcknowledgeComRecordsAsync(List{long}, string)"/>
        /// <seealso cref="ComRecordsAck"/>
        Task<bool> AcknowledgeComRecordAsync(long recordId, string loginName = null);

        /// <summary>
        /// Unacknowledges the communication records with the specified identifiers.
        /// </summary>
        /// <param name="recordIds">The list of com record identifiers to unacknowledge.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// <see langword="true"/> in case of success; <see langword="false"/> otherwise.
        /// </returns>
        /// <remarks>
        /// <para>
        /// A <see cref="ComRecordsUnAck"/> event is raised listing the identifiers of the com records
        /// that were actually unacknowledged.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <seealso cref="ComRecordsUnAck"/>
        Task<bool> UnacknowledgeComRecordsAsync(List<long> recordIds, string loginName = null);

        /// <summary>
        /// Unacknowledges the communication record with the specified identifier.
        /// </summary>
        /// <param name="recordId">The com record identifier.</param>
        /// <param name="loginName">The target user's login name.</param>
        /// <returns>
        /// <see langword="true"/> in case of success; <see langword="false"/> otherwise.
        /// </returns>
        /// <remarks>
        /// <para>
        /// A <see cref="ComRecordsUnAck"/> event is raised listing the identifiers of the com records
        /// that were actually unacknowledged.
        /// </para>
        /// <para>
        /// If the session has been opened for a user, the <c>loginName</c> parameter is ignored,
        /// but it is mandatory if the session has been opened by an administrator.
        /// </para>
        /// </remarks>
        /// <seealso cref="UnacknowledgeComRecordsAsync(List{long}, string)"/>
        /// <seealso cref="ComRecordsUnAck"/>
        Task<bool> UnacknowledgeComRecordAsync(long recordId, string loginName = null);
    }
}
